# Generated by Django 3.1 on 2020-08-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20200819_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='about_song',
            new_name='about_song1',
        ),
        migrations.RenameField(
            model_name='kamikaze',
            old_name='about_song',
            new_name='about_song1',
        ),
        migrations.RenameField(
            model_name='revival',
            old_name='about_song',
            new_name='about_song1',
        ),
        migrations.AddField(
            model_name='album',
            name='about_song2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kamikaze',
            name='about_song2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='revival',
            name='about_song2',
            field=models.TextField(blank=True),
        ),
    ]
