# Generated by Django 3.1 on 2020-08-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_auto_20200819_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='img',
        ),
        migrations.RemoveField(
            model_name='kamikaze',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='kamikaze',
            name='img',
        ),
        migrations.RemoveField(
            model_name='revival',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='revival',
            name='img',
        ),
    ]
