# Generated by Django 3.1 on 2020-08-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_auto_20200819_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamikaze',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='revival',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
