# Generated by Django 3.1 on 2020-08-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0005_lyrics_album_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='link',
        ),
    ]
