# Generated by Django 3.1 on 2020-08-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0006_remove_lyrics_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='img',
        ),
    ]
